services:
  dev_cogni:
    build:
      context: .
      dockerfile: ./Cogni/Dockerfile.dev
    restart: always
    ports:
      - 5279:5279
    volumes:
      - ./Cogni:/src/Cogni
      - ./Shared:/src/Shared
  dev_chat_service:
    build:
      context: .
      dockerfile: ./ChatService/Dockerfile.dev
    ports:
      - 5108:5108
    image: chat-backend
    restart: always
    volumes:
      - ./ChatService:/src/ChatService
      - ./Shared:/src/Shared
  dev_chat_frontend:
    build:
      context: ./ChatDevFrontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_DOCKER_DEV=true
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./ChatDevFrontend
          target: /app