FROM node:22.14.0-alpine
WORKDIR /app
COPY --link package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm install
COPY --link . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]